name: Clone Workflow
on:
  workflow_dispatch:
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: appleboy/ssh-actions@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /pub/amill164/
          git clone https://github.com/amiller164/cmsc389T-web-template.git
