name: Delete Workflow
on:
  workflow_dispatch:
jobs:
  delete:
    name: Delete
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: appleboy/ssh-actions@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /pub/amill164/
          unalias rm
          rm -rf cmsc389T-web-template
