name: Delete Workflow
on:
  workflow_dispatch:
jobs:
  delete:
    name: Delete_Workflow
    runs-on: Ubuntu-latest
    steps:
      name: Delete
      uses: appleboy/ssh-actions@master
      with:
        host: {{ secrets.HOST }}
        username: {{ secrets.USERNAME }}
        password: {{ secrets.PASSWORD }}
        port: {{ secrets.PORT }}
        script: |
          cd /pub/amill164/
          unalias rm
          rm -rf cmsc389T-web-template
